services:
  db:
    image: postgres:15-alpine
    container_name: logistic-order-db
    restart: unless-stopped
    shm_size: 256mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: logistic-order-redis
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  migrate:
    build:
      context: ./api
      target: builder
      args:
        BUILD_APP: "false"
    container_name: logistic-order-migrate
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PNPM_PACKAGE_IMPORT_CONFIRM: "false"
    networks:
      - backend
    command: sh -c "pnpm exec prisma migrate deploy"

  api:
    build:
      context: ./api
      args:
        BUILD_APP: "true"
    container_name: logistic-order-api
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - ./.env
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3030
    networks:
      - backend
      - frontend

  web:
    build:
      context: ./web
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3030/api
    container_name: logistic-order-web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3030/api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - frontend
      - backend 
    ports:
      - "3000:3000"

networks:
  backend:
    name: projeto-teste_backend
  frontend:
    name: projeto-teste_frontend
    driver: bridge